[phases.setup]
nixPkgs = ['...', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'gunicorn deployment_project.wsgi --bind 0.0.0.0:$PORT'
